import { slugify } from './utils/slugify';

export type RawProject = {
  id: string; // slug id
  name: string;
  live?: string;
  github?: string;
  description: string;
  stack: string[];
  category?: string;
  status?: 'Live' | 'In Development' | 'Archived' | 'Completed';
  year?: string;
};

// Helper to create an id from the provided project name if not already a slug
function id(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export const projects: RawProject[] = [
  {
    id: 'visheshdesignai',
    name: 'visheshdesignai',
    live: 'https://visheshdesignai.vercel.app',
    github: 'https://github.com/visheshsanghvi112/InteriorDesignAi',
    description: 'AI-powered interior design: upload a room photo and generate new design concepts.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Clerk', 'Replicate', 'shadcn/ui'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'chatbotspecial',
    name: 'chatbotspecial',
    live: 'https://chatbotspecial.vercel.app',
    github: 'https://github.com/visheshsanghvi112/chatbotspecial',
    description: 'LLM-powered chatbot for intelligent, context-aware conversations.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Clerk', 'Pinecone', 'LangChain', 'OpenAI'],
    category: 'AI Chatbot',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'api-checker',
    name: 'api-checker',
    live: 'https://api-checker-liart.vercel.app',
    github: 'https://github.com/visheshsanghvi112/model-probe',
    description: 'Quickly check the status and response of any API endpoint.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    category: 'Developer Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'vishesh-portfolio-sphere',
    name: 'vishesh-portfolio-sphere',
    live: 'https://visheshsanghvi.me',
    github: 'https://github.com/visheshsanghvi112/visheshsanghvi',
    description: 'Interactive portfolio with 3D sphere and modern animations.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Three.js', 'Framer Motion'],
    category: 'Portfolio',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'qrsaas',
    name: 'qrsaas',
    live: 'https://qrsaas.vercel.app',
    github: 'https://github.com/visheshsanghvi112/qrcode',
    description: 'SaaS for creating and managing QR codes with tracking.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Prisma', 'Stripe'],
    category: 'SaaS',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'fintech-template',
    name: 'fintech-template',
    live: 'https://fintech-template.vercel.app',
    github: 'https://github.com/visheshsanghvi112/fintech-template-123',
    description: 'Fintech dashboard template with charts and transactions.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Chart.js', 'Plaid'],
    category: 'Template',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'siriem-reimagined',
    name: 'siriem-reimagined',
    live: 'https://siriem-reimagined.vercel.app',
    github: 'https://github.com/visheshsanghvi112/siriem-reimagined-98',
    description: 'Reimagined media/content experience with fresh UI.',
    stack: ['Remix', 'React', 'TypeScript', 'Tailwind CSS'],
    category: 'Web App',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'bakerdavis',
    name: 'bakerdavis',
    live: 'https://bdindia.in',
    github: 'https://github.com/visheshsanghvi112/bd-pharma-vista',
    description: 'Corporate website for a pharmaceutical company.',
    stack: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    category: 'Corporate',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'ambica',
    name: 'ambica',
    live: 'https://ambicapharma.net',
    github: 'https://github.com/visheshsanghvi112/ambica-pharma-portal',
    description: 'Pharmaceutical company website with product showcase.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    category: 'Corporate',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'jhc-research',
    name: 'jhc-research',
    live: 'https://jhc-researchh.vercel.app',
    github: 'https://github.com/visheshsanghvi112/jhc-research-horizon-90',
    description: 'Research organization website with publications and profiles.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    category: 'Web App',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'lets-do-it',
    name: 'lets-do-it',
    live: 'https://lets-do-itt.vercel.app',
    github: 'https://github.com/visheshsanghvi112/done-it-now-landing-30',
    description: 'Landing page for a productivity/task management app.',
    stack: ['Remix', 'React', 'TypeScript', 'Tailwind CSS'],
    category: 'Landing',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'billifyy',
    name: 'billifyy',
    live: 'https://billifyy.vercel.app',
    github: 'https://github.com/visheshsanghvi112/billifyy',
    description: 'Invoice generator and management app for freelancers.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'Firebase'],
    category: 'Web App',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'friendly-readme-creator',
    name: 'friendly-readme-creator',
    live: 'https://friendly-readme-creator.vercel.app',
    github: 'https://github.com/visheshsanghvi112/friendly-readme-creator',
    description: 'Generate clean, comprehensive README files with templates.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI'],
    category: 'Developer Tool',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'readme',
    name: 'readme',
    live: 'https://readme-three-olive.vercel.app',
    github: 'https://github.com/visheshsanghvi112/friendly-readme-creator',
    description: 'Alternate deployment of README creator tool.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI'],
    category: 'Developer Tool',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'ai-n8n',
    name: 'ai-n8n',
    live: 'https://ai-n8n.vercel.app',
    github: 'https://github.com/visheshsanghvi112/dynamic-ai-agent-64',
    description: 'AI integrated with n8n for intelligent automated workflows.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'n8n'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'attendance-analyzer',
    name: 'attendance-analyzer',
    live: 'https://attendance-analyzer-wheat.vercel.app',
    github: 'https://github.com/visheshsanghvi112/attend-ai-insight-flow-79',
    description: 'Analyze attendance data and generate insights.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    category: 'Data Tool',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'pulse-robot',
    name: 'pulse-robot',
    live: 'https://pulse-robot-sigma.vercel.app',
    github: 'https://github.com/visheshsanghvi112/p-914120',
    description: 'Monitoring dashboard to keep a pulse on systems/services.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Dashboard',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'chess-by-vishesh',
    name: 'chess-by-vishesh',
    live: 'https://chess-by-vishesh.vercel.app',
    github: 'https://github.com/visheshsanghvi112/chess-duo-unite-play',
    description: 'Play chess on the web—multiplayer and/or vs AI.',
    stack: ['React', 'TypeScript', 'Tailwind CSS', 'chess.js', 'Socket.IO'],
    category: 'Game',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'travel',
    name: 'travel',
    live: 'https://travel-eta-wheat.vercel.app',
    github: 'https://github.com/visheshsanghvi112/a-522273',
    description: 'Travel planning/blogging experience.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Web App',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'interviewprep',
    name: 'interviewprep',
    live: 'https://interviewprep-red.vercel.app',
    github: 'https://github.com/visheshsanghvi112/data-interview-nexus-01',
    description: 'Interview prep hub, especially for data roles.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Education',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'thealgorithmclub',
    name: 'thealgorithmclub',
    live: 'https://thealgorithmclub.vercel.app',
    github: 'https://github.com/visheshsanghvi112/algorithm-nexus-web-17',
    description: 'Learn algorithms and data structures interactively.',
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
    category: 'Education',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'form-genius',
    name: 'form-genius',
    live: 'https://form-genius-theta.vercel.app',
    github: 'https://github.com/visheshsanghvi112/form-genius-engine-79',
    description: 'AI-powered form builder from natural language.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'gymkhaana',
    name: 'gymkhaana',
    live: 'https://gymkhaana.vercel.app',
    github: 'https://github.com/visheshsanghvi112/fit-fuel-fast',
    description: 'Gym/fitness website with schedules and membership info.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Business',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'cortexsecond-brain',
    name: 'cortexsecond-brain',
    live: 'https://cortexsecond-brain.vercel.app',
    github: 'https://github.com/visheshsanghvi112/c-666698',
    description: 'Personal knowledge management “second brain”.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'Firebase'],
    category: 'Productivity',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'ringsize',
    name: 'ringsize',
    live: 'https://ringsize.vercel.app',
    github: 'https://github.com/visheshsanghvi112/royal-ring-reign-65',
    description: 'Determine ring size with camera/on-screen guides.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Utility',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'ai-code-detection',
    name: 'ai-code-detection',
    live: 'https://ai-code-detection.vercel.app',
    github: 'https://github.com/visheshsanghvi112/code-integrity-scanner-03',
    description: 'Detect if code is human or AI-written using AI.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'resume-ai',
    name: 'resume-ai',
    live: 'https://resume-ai-one-tau.vercel.app',
    github: 'https://github.com/visheshsanghvi112/resume-insight-builder-62',
    description: 'AI-powered resume analysis and improvements.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'stats-made-easy',
    name: 'stats-made-easy',
    live: 'https://stats-made-easy.vercel.app',
    github: 'https://github.com/visheshsanghvi112/stat-whisperer-visuals',
    description: 'Learn statistics with visuals and interactivity.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'D3.js'],
    category: 'Education',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'rekhta-realms',
    name: 'rekhta-realms',
    live: 'https://rekhta-realms.vercel.app',
    github: 'https://github.com/visheshsanghvi112/rekhta-roman-verse-22',
    description: 'Urdu poetry (Rekhta) in Roman script for accessibility.',
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind CSS'],
    category: 'Culture',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'chess-by-vs',
    name: 'chess-by-vs',
    live: 'https://chess-by-vs.vercel.app',
    github: 'https://github.com/visheshsanghvi112/sanghvi-chess-masterpiece-39',
    description: 'Another web chess project variation.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'chess.js'],
    category: 'Game',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'bills-generator',
    name: 'bills-generator',
    live: 'https://bills-generator.vercel.app',
    github: 'https://github.com/visheshsanghvi112/BillsGenerator-',
    description: 'Simple bill/invoice generator tool.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Utility',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'future-chess',
    name: 'future-chess',
    live: 'https://future-chess.vercel.app',
    github: 'https://github.com/visheshsanghvi112/t-618158',
    description: 'Chess with a futuristic themed UI.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'chess.js'],
    category: 'Game',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'convrtai',
    name: 'convrtai',
    live: 'https://convrtai.vercel.app',
    github: 'https://github.com/visheshsanghvi112/convrtai',
    description: 'AI-powered conversation tools.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'learnbitcoin',
    name: 'learnbitcoin',
    live: 'https://bitcoinlearn.vercel.app',
    github: 'https://github.com/visheshsanghvi112/block-byte-insights',
    description: 'Educational site for Bitcoin and blockchain.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Education',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'crypto',
    name: 'crypto',
    live: 'https://crypto-two-sepia.vercel.app',
    github: 'https://github.com/visheshsanghvi112/c-503186',
    description: 'Crypto markets dashboard/portfolio.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Finance',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'pdf-merge',
    name: 'pdf-merge',
    live: 'https://pdf-merge-pearl.vercel.app',
    github: 'https://github.com/visheshsanghvi112/p-013807',
    description: 'Merge multiple PDFs into one file.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'pdf-lib'],
    category: 'Utility',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'meal-flow-ai-planner',
    name: 'meal-flow-ai-planner',
    live: 'https://meal-flow-ai-planner.vercel.app',
    github: 'https://github.com/visheshsanghvi112/meal-flow-ai-planner-53',
    description: 'AI-powered meal planning for dietary goals.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'agent-haven-cloud',
    name: 'agent-haven-cloud',
    live: 'https://agent-haven-cloud.vercel.app',
    github: 'https://github.com/visheshsanghvi112/a-609842',
    description: 'Create/manage AI agents platform.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'AI Tool',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'curva-nord-rebellion',
    name: 'curva-nord-rebellion',
    live: 'https://curva-nord-rebellion.vercel.app',
    github: 'https://github.com/visheshsanghvi112/curva-nord-rebellion-online',
    description: 'Fan website experience for a sports team.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Fan Site',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'seasidestay',
    name: 'seasidestay',
    live: 'https://seasidestay.vercel.app',
    github: 'https://github.com/visheshsanghvi112/m-923127',
    description: 'Seaside hotel/vacation rental site.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Business',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'startcoding',
    name: 'startcoding',
    live: 'https://startcoding-beta.vercel.app',
    github: 'https://github.com/visheshsanghvi112/code-pal-playground-79',
    description: 'Online code playground using Monaco.',
    stack: ['React', 'Vite', 'Monaco'],
    category: 'Developer Tool',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'worldsbyvishesh',
    name: 'worldsbyvishesh',
    live: 'https://worldsbyvishesh.vercel.app',
    github: 'https://github.com/visheshsanghvi112/worldsbyvishesh',
    description: 'Creative personal site showcasing different “worlds”.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'Three.js'],
    category: 'Portfolio',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'vishesh-chatbot',
    name: 'vishesh-chatbot',
    live: 'https://visheshai.vercel.app',
    github: 'https://github.com/visheshsanghvi112/visheshChatbot',
    description: 'Personal chatbot powered by AI.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'OpenAI'],
    category: 'AI Chatbot',
    status: 'Live',
    year: '2025',
  },
  {
    id: 'visheshsanghvi',
    name: 'visheshsanghvi',
    live: 'https://visheshsanghvi.vercel.app',
    github: 'https://github.com/visheshsanghvi112/vishesh',
    description: 'Personal portfolio hub.',
    stack: ['React', 'Next.js', 'Tailwind CSS'],
    category: 'Portfolio',
    status: 'Live',
    year: '2023',
  },
  {
    id: 'bini',
    name: 'bini',
    live: 'https://bini-five.vercel.app',
    github: 'https://github.com/visheshsanghvi112/s-dreamscape-gallery',
    description: 'Gallery app for showcasing visual work.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Gallery',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'binii',
    name: 'binii',
    live: 'https://binii.vercel.app',
    github: 'https://github.com/visheshsanghvi112/s-dreamscape-gallery',
    description: 'Alternate gallery deployment.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Gallery',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'dialoguedhoom',
    name: 'dialoguedhoom',
    live: 'https://dialoguedhoom.vercel.app',
    github: 'https://github.com/visheshsanghvi112/dialogue-dhoom-mobile-game',
    description: 'React Native / Expo mobile game centered on dialogues.',
    stack: ['React Native', 'Expo'],
    category: 'Game',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'learnsyntax',
    name: 'learnsyntax',
    live: 'https://learnsyntax.vercel.app',
    github: 'https://github.com/visheshsanghvi112/syntax-adventures-lab',
    description: 'Interactive tool for learning programming syntax.',
    stack: ['React', 'Vite', 'Tailwind CSS'],
    category: 'Education',
    status: 'Live',
    year: '2024',
  },
  {
    id: 'v0-vishesh-swb5fss4qno',
    name: 'v0-vishesh-swb5fss4qno',
    live: 'https://v0-vishesh-swb5fss4qno.vercel.app',
    github: undefined,
    description: 'Prototype generated by Vercel v0 generative UI tool.',
    stack: ['React', 'Next.js', 'Tailwind CSS'],
    category: 'Prototype',
    status: 'Live',
    year: '2024',
  },
];

export default projects;
